#wait
ExplicitWait=5
timeOutDuration=5000

appiumPath = /usr/local/lib/node_modules/appium/build/lib/main.js
path_apk=src/main/resources/application/android/app-production-universal-debug.apk

#deviceName1 = pixel3-STAV
#deviceName2 = Mi_A1
platformName = Android
platformVersion = 9.0
serverIP = 127.0.0.1
appPackage = com.google.android.apps.nexuslauncher
appActivity = com.google.android.apps.nexuslauncher
skipUnlock = true
noReset = false
udid1 = 8B5Y0TYFT
udid2 = 0139fd039805

#Twilio
account_sid_dev=AC67ce8a0edcff2a8b58c1c7fe394b091e
account_sid_prod=AC2608f8b09c6e56ffa0a9dce9d1e20003
auth_token_dev=898183bc3f177f48395360bfaebaecaf
auth_token_prod=b8789b118cb77bb56b3d0e20da4861b2
TWILIO_POLLING_INTERVAL = 2000
smsNumOfRepeat = 3

#jsons
usersJson=src/test/resources/requestBodyTemplates/loginUers.json
gatheringJson=src/test/resources/requestBodyTemplates/gatherings.json
rideJson=src/test/resources/requestBodyTemplates/rides.json
taxiJson=src/test/resources/requestBodyTemplates/taxiOrder.json
inviteesJson=src/test/resources/requestBodyTemplates/invitees.json

