#wait
ExplicitWait=5
timeOutDuration=5000

appiumPath = /usr/local/lib/node_modules/appium/build/lib/main.js
path_apk=src/main/resources/application/android/app-production-universal-debug.apk

#deviceName1 = pixel3-STAV
#deviceName2 = Mi_A1
platformName = Android
platformVersion = 9.0
serverIP = 127.0.0.1
appPackage = com.google.android.apps.nexuslauncher
appActivity = com.google.android.apps.nexuslauncher
skipUnlock = true
noReset = false
udid1 = 8B5Y0TYFT
udid2 = 0139fd039805

#jsons
usersJson=src/test/resources/requestBodyTemplates/loginUers.json
gatheringJson=src/test/resources/requestBodyTemplates/gatherings.json
rideJson=src/test/resources/requestBodyTemplates/rides.json
taxiJson=src/test/resources/requestBodyTemplates/taxiOrder.json
inviteesJson=src/test/resources/requestBodyTemplates/invitees.json

